In [1]:
import numpy as np

# Sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [2]:
# Derivative of sigmoid function
def sigmoid_derivative(x):
    return x * (1 - x)

In [3]:
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

y = np.array([[0], [0], [0], [1]])

In [4]:

weights = np.random.rand(2, 1)
bias = np.random.rand(1)

learning_rate = 0.01
epochs = 10000

In [5]:
# Training loop
for epoch in range(epochs):
    # Forward pass
    input_layer = X
    weighted_sum = np.dot(input_layer, weights) + bias
    activated_output = sigmoid(weighted_sum)
    print(activated_output)
    # Calculate the error
    error = y - activated_output

    # Backpropagation
    adjustment = error * sigmoid_derivative(activated_output)
    weights += np.dot(input_layer.T, adjustment) * learning_rate
    bias += np.sum(adjustment) * learning_rate

[[0.5947518 ]
 [0.70150794]
 [0.68190731]
 [0.77441229]]
[[0.59379038]
 [0.70044686]
 [0.68080603]
 [0.77333656]]
[[0.59282905]
 [0.69938483]
 [0.67970409]
 [0.77225874]]
[[0.59186784]
 [0.69832192]
 [0.67860153]
 [0.77117887]]
[[0.59090678]
 [0.69725814]
 [0.67749839]
 [0.770097  ]]
[[0.58994589]
 [0.69619355]
 [0.67639471]
 [0.76901318]]
[[0.5889852 ]
 [0.69512818]
 [0.67529053]
 [0.76792744]]
[[0.58802474]
 [0.69406207]
 [0.6741859 ]
 [0.76683983]]
[[0.58706453]
 [0.69299526]
 [0.67308085]
 [0.76575041]]
[[0.5861046 ]
 [0.69192778]
 [0.67197543]
 [0.76465922]]
[[0.58514499]
 [0.69085969]
 [0.67086969]
 [0.76356629]]
[[0.58418571]
 [0.68979102]
 [0.66976366]
 [0.7624717 ]]
[[0.58322679]
 [0.6887218 ]
 [0.66865738]
 [0.76137547]]
[[0.58226826]
 [0.68765208]
 [0.66755089]
 [0.76027765]]
[[0.58131015]
 [0.6865819 ]
 [0.66644425]
 [0.75917831]]
[[0.58035248]
 [0.68551129]
 [0.66533748]
 [0.75807748]]
[[0.57939528]
 [0.6844403 ]
 [0.66423064]
 [0.75697521]]
[[0.57843858]
 [0.68336897]
 [0

In [6]:
# Test the trained model
print("Final weights:", weights)
print("Final bias:", bias)

# Testing the AND gate
print("Testing the AND gate:")
for i in range(len(X)):
    input_data = X[i]
    output = sigmoid(np.dot(input_data, weights) + bias)
    print(f"Input: {input_data}, Output: {np.round(output)}")

Final weights: [[2.62801652]
 [2.62826983]]
Final bias: [-4.06766696]
Testing the AND gate:
Input: [0 0], Output: [0.]
Input: [0 1], Output: [0.]
Input: [1 0], Output: [0.]
Input: [1 1], Output: [1.]
